apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-reverseproxy
  labels:
    service: udacity-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udacity-reverseproxy
  template:
    metadata:
      labels:
        service: udacity-reverseproxy
    spec:
      containers:
        - image: jeanfern5/udacity-reverseproxy
          name: udacity-reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always


