apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-frontend
  labels:
    service: udacity-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udacity-frontend
  template:
    metadata:
      labels:
        service: udacity-frontend
        api: external
    spec:
      containers:
        - image: jeanfern5/udacity-frontend:local
          name: udacity-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always

